language: python
cache: pip
python:
  - "2.7"

before_script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then export PYTHON_EXE=pypy; export PIP_EXE=pip; else export PYTHON_EXE=python; fi

install:
  - pip install -U spec-checker

script: spec-checker --config spec-checker.conf requirements.md design.md
